use_frameworks!

target 'flutter_Example' do
  pod 'flutter', :path => '../'

  target 'flutter_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
        end
    end
end

target.headers_build_phase.files.each do |file|
    file.settings = { 'ATTRIBUTES' => ['Public'] }
end
